[package]
name = "blanket-codecs"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
blanket-core = { path = "../core" }
pyo3 = { version = "0.29", features = ["abi3-py312"] }
blanket-codec-common = { path = "../codec-common" }
blanket-codec-png = { path = "../codec-png" }
blanket-codec-jpeg = { path = "../codec-jpeg" }
blanket-codec-jxl = { path = "../codec-jxl" }
blanket-codec-heif = { path = "../codec-heif" }
blanket-codec-pdf = { path = "../codec-pdf" }
blanket-codec-tiff = { path = "../codec-tiff" }
blanket-codec-webp = { path = "../codec-webp" }
blanket-codec-avif = { path = "../codec-avif" }
blanket-codec-bmp-ico = { path = "../codec-bmp-ico" }
blanket-codec-gif = { path = "../codec-gif" }

[features]
default = []
jxl-vendored = ["blanket-codec-jxl/jxl-vendored"]
embedded-libheif = ["blanket-codec-heif/embedded-libheif"]
no-vendored-webp = ["blanket-codec-webp/no-vendored-webp"]

[lib]
doctest = false

[lints]
workspace = true
