[package]
name = "blanket-codecs"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
blanket-core = { path = "../core" }
blanket-ops = { path = "../ops" }
pyo3 = { version = "0.29", features = ["abi3-py312"] }
png = { version = "0.18", default-features = false, features = ["zlib-rs"]}
libheif-rs = { version = "3.0", default-features = false, features = ["latest"] }
image = { version = "0.25", default-features = false, features = ["png", "bmp", "gif", "ico", "rayon", "tiff", "webp", "avif", "avif-native", "nasm"] }
tiff = { version = "0.11", default-features = false, features = ["deflate", "lzw"]}
webpx = "0.4"
libwebp-sys = { version = "0.14", default-features = false, features = ["std", "parallel"] }
jpegxl-rs = { version = "0.15", default-features = false }
turbojpeg = { version = "1.5", default-features = false, features = ["cmake", "require-simd"] }
rayon = {version = "1.12", default-features = false }

[target.'cfg(target_arch = "aarch64")'.dependencies]
libwebp-sys = { version = "0.14", default-features = false, features = ["neon"] }

[target.'cfg(target_arch = "x86_64")'.dependencies]
libwebp-sys = { version = "0.14", default-features = false, features = ["avx2", "sse41"] }

[features]
default = []
jxl-vendored = ["jpegxl-rs/vendored"]
embedded-libheif = ["libheif-rs/embedded-libheif"]
no-vendored-webp = ["libwebp-sys/system-dylib"]

[lib]
doctest = false

[lints]
workspace = true
