[package]
name = "blanket-codec-jpeg"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
blanket-core = { path = "../core" }
pyo3 = { version = "0.29", features = ["abi3-py312"] }
blanket-codec-common = { path = "../codec-common" }
turbojpeg = { version = "1.5", default-features = false, features = ["cmake", "require-simd"] }
rayon = {version = "1.12", default-features = false }

[lib]
doctest = false

[lints]
workspace = true
