[package]
name = "blanket-compressor"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
blanket-core = { path = "../core" }
blanket-codecs = { path = "../codecs" }
blanket-ops = { path = "../ops" }
pyo3 = { version = "0.29", features = ["abi3-py312"] }
png = { version = "0.18", default-features = false, features = ["zlib-rs"]}
rayon = {version = "1.12", default-features = false }

[dev-dependencies]
turbojpeg = { version = "1.5", default-features = false, features = ["cmake", "require-simd"] }

[lib]
doctest = false

[lints]
workspace = true
