[package]
name = "blanket-stat"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
pyo3 = { version = "0.29", features = ["abi3-py312"] }

[lib]
doctest = false

[lints]
workspace = true
