[package]
name = "blanket-codec-jxl"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
blanket-core = { path = "../core" }
pyo3 = { version = "0.29", features = ["abi3-py312"] }
blanket-codec-common = { path = "../codec-common" }
jpegxl-rs = { version = "0.16", default-features = false }
jpegxl-sys = { version = "0.13", default-features = false }
rayon = {version = "1.12", default-features = false }

[features]
default = []
jxl-vendored = ["jpegxl-rs/vendored"]

[lib]
doctest = false

[lints]
workspace = true
