[package]
name = "blanket"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
publish = false

[lib]
name = "_blanket"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29", features = ["abi3-py312"] }
blanket-core = { path = "../core" }
blanket-codecs = { path = "../codecs" }
blanket-ops = { path = "../ops" }

[features]
default = ["vendored"]
vendored = ["blanket-codecs/vendored"]
embedded-libheif = ["blanket-codecs/embedded-libheif"]
user-provided-webp = ["blanket-codecs/user-provided-webp"]

[lints]
workspace = true